services:
  db-products:
    image: postgres:17
    container_name: db-products
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=product_password
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    networks:
      backend:
    ports:
      - "5436:5432"

networks:
  backend:

volumes:
  postgres_product_data:
