services:
  db-products:
    image: postgres:17
    container_name: db-products
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=product_password
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    networks:
      backend:
    ports:
      - "5436:5432"

  stock-ms:
    image: stock-ms
    container_name: stock
    build:
      context: .
    environment:
      - DB_SERVER=db:5436
      - POSTGRES_DB=products_db
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=products_db
      - EUREKA_SERVER=server-eureka
      - EUREKA=eureka
    networks:
      backend:
    restart: always

networks:
  backend:

volumes:
  postgres_product_data:
